-- Inital config
vim.keymap.set("n", "<C-z>", "<C-w>", { noremap = true })
vim.keymap.set("n", "<C-z>", "<nop>")
vim.keymap.set('n', '<F7>', ':sp<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F8>', ':vs<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F9>', ':FloatermToggle<CR>', { noremap=true, silent=true })
vim.keymap.set('n', 'q', ':q<CR>', { noremap=true, silent=true })
vim.keymap.set('n', 'qq', ':q!<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<C-h>', '<CMD>vertical resize -1<CR>', { silent = true })
vim.keymap.set('n', '<C-l>', '<CMD>vertical resize +1<CR>', { silent = true })
vim.keymap.set('n', '<C-j>', '<CMD>resize +1<CR>', { silent = true })
vim.keymap.set('n', '<C-k>', '<CMD>resize -1<CR>', { silent = true })

-- Advanced config
vim.keymap.set('n', '<F1>', ':Telescope find_files<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F2>', ':Telescope current_buffer_fuzzy_find<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F3>', ':Telescope live_grep<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F4>', ':Telescope oldfiles<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F5>', ':NvimTreeToggle<CR>', { noremap=true, silent=true })
vim.keymap.set("n", "<F12>", "<cmd>AerialToggle!<CR>", { noremap=true, silent=true })
