-- Inital config
vim.keymap.set('n', 'q', ':q<CR>', { noremap=true, silent=true })
vim.keymap.set('n', 'qq', ':q!<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<C-Left>', '<CMD>vertical resize -1<CR>', { silent = true })
vim.keymap.set('n', '<C-Right>', '<CMD>vertical resize +1<CR>', { silent = true })
vim.keymap.set('n', '<C-Down>', '<CMD>resize +1<CR>', { silent = true })
vim.keymap.set('n', '<C-Up>', '<CMD>resize -1<CR>', { silent = true })
vim.keymap.set('n', '<C-h>', '<C-w>h', { noremap=true, silent=true })
vim.keymap.set('n', '<C-j>', '<C-w>j', { noremap=true, silent=true })
vim.keymap.set('n', '<C-k>', '<C-w>k', { noremap=true, silent=true })
vim.keymap.set('n', '<C-l>', '<C-w>l', { noremap=true, silent=true })

-- Advanced config
vim.keymap.set('n', '<F1>', ':Telescope find_files<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F2>', ':Telescope current_buffer_fuzzy_find<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F3>', ':Telescope live_grep<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F4>', ':Telescope oldfiles<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F5>', ':Telescope grep_string<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F6>', ':NvimTreeToggle<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F7>', ':sp<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F8>', ':vs<CR>', { noremap=true, silent=true })
vim.keymap.set('n', '<F9>', ':FloatermToggle<CR>', { noremap=true, silent=true })
vim.keymap.set("n", "<F11>", function() return ":IncRename " .. vim.fn.expand("<cword>") end, { expr = true })
vim.keymap.set("n", "<F12>", "<cmd>AerialToggle!<CR>", { noremap=true, silent=true })
